plugins:
  unikname_connect_enabled:
    default: false
    client: true
  unikname_connect_business_account_id:
    default: ""
  unikname_connect_api_secret_key:
    default: ""
  unikname_connect_allow_association_change:
    default: false
  unikname_connect_overrides_email:
    default: false
  unikname_connect_verbose_logging:
    default: false
